project:
  type: book
  output-dir: docs

lang: pt

#listing: 
  #categories: true

book:
  # title: "Professor Robson"
  author: "Prof. Robson"
  #date: "4/24/2023"
  page-navigation: true
  chapters:
    - index.qmd
    - escolas/escolas.qmd
    #- summary.qmd
    - part: literatura/literatura.qmd ### LITERATURA
      chapters:
          - literatura/romantismo-prosa.qmd
          - literatura/livro-iracema.qmd
          - literatura/naturalismo.qmd
          - literatura/o-cortico.qmd
          - literatura/pre-modernismo.qmd
          - literatura/euclides-cunha.qmd
          - literatura/lima-barreto.qmd
          - literatura/monteiro-lobato.qmd
          - literatura/augusto-anjos.qmd
    - part: redacao/redacao.qmd ### REDAÇÃO
      chapters:
          - redacao/cronica-scliar.qmd
          - redacao/carta-argumentativa-proposta-01.qmd
    - part: gramatica/gramatica.qmd ### GRAMÁTICA
      chapters:
          - gramatica/gramatica.qmd
    - part: escolas/escolas.qmd ### GRAMÁTICA
      chapters:
          - escolas/2eefe_conteudo.qmd
          - escolas/1eemp_conteudo.qmd
          - escolas/2eemp_conteudo.qmd
          - escolas/3eemp_conteudo.qmd
    #- references.qmd
  #appendices:
    #- cap_01.qmd
    #- cap_01.qmd
  page-footer:
    center: 
      - text: "Prefácio"
        href: index.qmd

#sidebar: 
  #collapse: true

number-sections: false
    
    
bibliography: references.bib # exportar como "Better BibLaTeX"
#csl: abnt-ufmg.csl # NÃO USAR!!!

format:
  html:
    theme:
      dark: solar #slate #darkly #superhero #flatly #sketchy #lux #litera #darkly #superhero
      light: flatly #litera
    code-copy: true
    linestretch: 1.5 # Espaçamento de linha (padrão = 1.5)
    margin-left: 00mm
    margin-right: 00mm
    margin-top: 00mm
    margin-bottom: 00mm
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
highlight-style: pygments

editor: source

reference-location: margin
citation-location: margin
fig-cap-location: bottom
tbl-cap-location: top
fig-align: center

fontsize: 18px # Default: 18px
