---
title: "📕 1º ANO: Conteúdo"
categories: [Literatura]
---

[Escolas](escolas.html)

# Conteúdo programático

<!-- 1º bimestre -------------------------------------------------------------->
## 1º bimestre
- **Conceitos fundamentais:**
- [ ] língua,
- [ ] linguagem,
- [ ] fala,
- [ ] signo linguístico.
- [ ] Variação linguística.
- [ ] Elementos da comunicação e função de linguagem.
- **Sequência textual:**
- [ ] descritiva e injuntiva
- Gênero textual:
- [ ] relato,
- [ ] crônicas memorialísticas,
- [ ] diário,
- [ ] perfil,
- [ ] autobiografia e outros.
- **Literatura:**
- [ ] Conceito de literatura
- [ ] Gênero literário
- [ ] **Sugestão de leitura:** Quarto do despejo, Maria Carolina de Jesus
- **Produção de texto:**
- [ ] Elaboração do gênero perfil;
- [ ] Produção de relatos;
- [ ] Elaboração de receitas.
- **Análise linguística:**
- [ ] o papel do adjetivo e do numeral na construção de sentido do texto.

<!-- 2º bimestre -------------------------------------------------------------->
## 2º bimestre
- **Tipos e Gêneros Textuais:**
- [ ] Sequência textual: narrativo: elementos da narrativa.
- [ ] Sequência textual: expositiva.
- [ ] Gêneros textuais: notícia, reportagem, conto, crônica, fábula, dentre outros
- [ ] Relação entre partes de textos narrativos.
- [ ] Denotação e conotação.
- [x] Figuras de linguagem.
- [ ] Análise linguística: o papel do substantivo e do artigo na construção de sentido do texto.
- **Literatura:**
- [x] Trovadorismo.
- [ ] Humanismo.
- [ ] Sugestão de leitura: O auto da Compadecida de Ariano Suassuna e Auto da barca do inferno, de Gil Vicente.
- **Produção de texto:** 
- [ ] notícia


<!-- 3º bimestre -------------------------------------------------------------->
## 3º bimestre
- [ ] Intertextualidade e interdiscursividade.
Sequência textual: argumentativa.
Gêneros textuais: texto de opinião, crônicas argumentativas, resenhas, dentre outros. Relação entre partes de textos argumentativos.
Coesão e coerência.
Estrutura e processos de formação de palavras.
Literatura:
1- Quinhentismo
2- Classicismo
3- Sugestão de leitura: O Karaíba de Daniel Munduruku.
Produção de texto: texto de opinião.
Análise linguística: o papel dos conectivos na construção de sentido.

<!-- 4º bimestre -------------------------------------------------------------->
## 4º bimestre
Operadores argumentativos.
Modalizadores do discurso.
Gêneros textuais: carta argumentativa, carta aberta, carta de solicitação, carta de recomendação. Semântica: sinonímia, antonímia, hiponímia, hiperonímia, homonímia, polissemia, amibiguidade. Literatura:
1- Barroco;
2- Arcadismo;
3- Sugestão de leitura: seleção de contos, crônicas e poemas.
Análise linguística: noções de ortografia, acentuação e pontuação.